# Generated by Django 4.2.11 on 2025-03-30 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPlace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('is_reserved', models.BooleanField(default=False)),
                ('is_occupied', models.BooleanField(default=False)),
                ('is_charging', models.BooleanField(default=False)),
                ('reservation_end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Events Places',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('ongoing', 'Ongoing'), ('done', 'Done')], default='pending', max_length=10)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.eventplace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reservations',
                'ordering': ['-start_time'],
            },
        ),
        migrations.DeleteModel(
            name='Extracurricular',
        ),
    ]
