# Generated by Django 4.2.11 on 2025-03-30 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_eventplace_reservation_delete_extracurricular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='spot',
            new_name='room',
        ),
        migrations.RemoveField(
            model_name='eventplace',
            name='is_charging',
        ),
    ]
