# Generated by Django 4.2.11 on 2025-03-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_rename_spot_reservation_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='faculty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
